export const chatData = [
  {
    profile: "/images/Ellipse.png",
    name: "John Doe",
    isFavorite: false,
    isOnline: true,
    lastMessageDateTime: "20:12",
    isSeen: true,
    lastMessage: {
      isLast: "text",
      message:
        "Two blue ticks, and one red tick means the government can take action",
    },
  },
  {
    profile: "/images/Ellipse-1.png",
    isOnline: true,
    lastMessageDateTime: "05/06",
    name: "Janifer",
    isFavorite: true,
    isSeen: false,
    lastMessage: {
      isLast: "call",
      message: "Missed call",
    },

    isSeen: true,
  },
  {
    profile: "/images/Ellipse-2.png",
    isOnline: false,
    lastMessageDateTime: "20:12",
    isFavorite: true,
    name: "Charlie",
    isSeen: false,
    pendingToSeen: 3,
    lastMessage: {
      isLast: "text",
      message: `Now, such WhatsApp messages are commonplace in today’s time. A similar message was doing the rounds on WhatsApp around last year as well with similar claims of “red ticks" indicating government action against WhatsApp users.`,
    },
  },
  {
    profile: "/images/Ellipse-3.png",
    lastMessageDateTime: "20:12",
    isOnline: true,
    isFavorite: false,
    name: "David",
    isSeen: true,
    lastMessage: {
      isLast: "text",
      message: "30 Photos That People Should’ve Checked Before Posting",
    },
  },
  {
    profile: "/images/Ellipse-4.png",
    isFavorite: false,
    lastMessageDateTime: "20:12",
    isOnline: true,
    name: "Alex",
    isSeen: true,
    lastMessage: {
      isLast: "text",
      message: `message is doing the rounds claiming that the government may have control over users’ WhatsApp. This is a false message as WhatsApp has not made any changes to its system and the government does not have access to anyone’s WhatsApp. The message reads - “Two blue ticks, and one red tick means the government can take action`,
    },
  },
  {
    profile: "/images/Ellipse-5.png",
    isOnline: true,
    isFavorite: false,
    isSeen: false,
    pendingToSeen: 1,
    lastMessageDateTime: "05/06",
    name: "Andrew",
    lastMessage: {
      isLast: "text",
      message: "Hello World",
    },
  },
  {
    profile: "/images/Ellipse.png",
    name: "John Doe",
    isFavorite: false,
    isOnline: true,
    lastMessageDateTime: "20:12",
    isSeen: true,
    lastMessage: {
      isLast: "text",
      message:
        "Two blue ticks, and one red tick means the government can take action",
    },
  },
  {
    profile: "/images/Ellipse-1.png",
    isOnline: true,
    lastMessageDateTime: "05/06",
    name: "Janifer",
    isFavorite: true,
    isSeen: false,
    lastMessage: {
      isLast: "call",
      message: "Missed call",
    },

    isSeen: true,
  },
  {
    profile: "/images/Ellipse-2.png",
    isOnline: false,
    lastMessageDateTime: "20:12",
    isFavorite: true,
    name: "Charlie",
    isSeen: false,
    pendingToSeen: 3,
    lastMessage: {
      isLast: "text",
      message: `Now, such WhatsApp messages are commonplace in today’s time. A similar message was doing the rounds on WhatsApp around last year as well with similar claims of “red ticks" indicating government action against WhatsApp users.`,
    },
  },
  {
    profile: "/images/Ellipse-3.png",
    lastMessageDateTime: "20:12",
    isOnline: true,
    isFavorite: false,
    name: "David",
    isSeen: true,
    lastMessage: {
      isLast: "text",
      message: "30 Photos That People Should’ve Checked Before Posting",
    },
  },
  {
    profile: "/images/Ellipse-4.png",
    isFavorite: false,
    lastMessageDateTime: "20:12",
    isOnline: true,
    name: "Alex",
    isSeen: true,
    lastMessage: {
      isLast: "text",
      message: `message is doing the rounds claiming that the government may have control over users’ WhatsApp. This is a false message as WhatsApp has not made any changes to its system and the government does not have access to anyone’s WhatsApp. The message reads - “Two blue ticks, and one red tick means the government can take action`,
    },
  },
  {
    profile: "/images/Ellipse-5.png",
    isOnline: true,
    isFavorite: false,
    isSeen: false,
    pendingToSeen: 1,
    lastMessageDateTime: "05/06",
    name: "Andrew",
    lastMessage: {
      isLast: "text",
      message: "Hello World",
    },
  },
];
